### PR TITLE
Translates site to portuguese

### PR DESCRIPTION
**Pull request by augustohp**
We can now start to translate the site to Portuguese, thanks to @nelsonsar. Apart from the translations, there are still some issues:

* [ ] Language switcher (not working on all pages)
* [x] Enable translation of articles
* [ ] Enable translation of collections from YAML data sources.

### CODE REVIEW

**Comment by nelsonsar** [comment]
@augustohp the language selector doesn't work in some pages or all of them?

**Comment by augustohp** [comment]
> @augustohp the language selector doesn't work in some pages or all of them?

All of them. I've updated the "task".

**Comment by osmar-vil** [comment]
How I can participate in this project?

**Comment by lflimeira** [comment]
@osmar-vil you can translate the files in the Pull Request, help sharing the event and this repository and you can also participate of the PHP TestFest that will happen all over the world.

**Comment by leonampd** [comment]
Hey everyone,

I opened #3  for the BR version.

**Pull request closed without merging**
